---
svc_name: "justrade gateway"
service_type: simple
service_enable: true
service_exec: "{{ install_dir }}/bin/gateway.sh"
gateway_config_path: /etc/justrade/gateway.properties
service_env:
  JUSTRADE_CONFIG: "{{ gateway_config_path }}"
  JUSTRADE_JAVA_OPTS: "{{ gateway_java_opts }}"
